<?php

/**
 * @file
 * A configurable Block containing your blogroll from Google Reader.
 */


/**
 * Implementation of hook_menu().
 */
function gr_blogroll_menu() {
    $items['admin/settings/blogroll'] = array(
      'title' => t('Blogroll'),
      'page callback' => 'drupal_get_form',
      'page arguments' => array('gr_blogroll_admin_settings'),
      'access arguments' => array('administer site configuration'),
      'description' => t('Configure the Blogroll to get data from your Google Reader shared items.'),
    );
    return $items;
}

function gr_blogroll_admin_settings() {
  $form['gr_blogroll_url'] = array(
      '#type' => 'textfield',
      '#title' => t('Google Reader blogroll URL'),
      '#default_value' => variable_get('gr_blogroll_url', false),
      '#description' => t('Enter the blogroll URL from your Google Reader Tag.'),
  );
  return system_settings_form($form);
}

/**
 * Implementation of hook_block().
 *
 * Display your blogroll from Google Reader
 */
function gr_blogroll_block($op = 'list', $delta = 0) {
  global $user;
  if ($op == 'list') {
    $block[0]['info'] = t('Blogroll');
  }
  elseif ($op == 'view') {
	  $items = _gr_blogroll_parse_url();
    if (user_access('access content') && sizeof($items) > 0 ) {
	    $block['subject'] = t('My Blogroll');
	    $block['content'] = theme('item_list',$items,NULL,'ul',array("id"=>"blogroll"));
    }
  }
  return $block;
}

function _gr_blogroll_parse_url() {
  $url = variable_get('gr_blogroll_url', false);
  $items = array();
  if ($url){
     $url_token = str_replace("http://www.google.com/reader/shared/","",urldecode($url));
     $json_url = "http://www.google.com/reader/public/javascript-sub/".$url_token;

     $file  = drupal_http_request($json_url);
     $json = json_decode($file->data);
    
     $json_items = $json->items;
		 if (sizeof($json_items) > 0) {
	     foreach($json_items as $key=>$item) {
	       $items[] = l($item->title,trim($item->alternate->href),array('title'=>$item->title),null,null,false,true);
	     }
			
	   }
  }
  return $items;
}